version: '3.8'

services:
  # Redis for API key storage (optional)
  redis:
    image: redis:7-alpine
    container_name: erp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - erp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Identity Service - API Key Management
  identity-service:
    build:
      context: .
      dockerfile: src/Services/ERP.IdentityService/Dockerfile
    container_name: erp-identity-service
    ports:
      - "5007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - erp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Weather Service - Main Application Service
  weather-service:
    build:
      context: .
      dockerfile: src/Services/Playground.WeatherService/Dockerfile
    container_name: erp-weather-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - erp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # BFF Gateway - API Gateway with Authentication
  bff-gateway:
    build:
      context: .
      dockerfile: src/Gateway/BFF.Gateway/Dockerfile
    container_name: erp-bff-gateway
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityService__RestUrl=http://identity-service:8080
    depends_on:
      identity-service:
        condition: service_healthy
      weather-service:
        condition: service_healthy
    networks:
      - erp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  erp-network:
    driver: bridge
