# ============================================================================
# ERP PROTOTYPE - UNIFIED INFRASTRUCTURE DOCKER COMPOSE
# ============================================================================
# This Docker Compose file defines the complete infrastructure stack for the
# ERP Prototype system, including:
#
# 📦 REDIS STACK:      Caching and session storage
# 📊 ELK STACK:        Centralized logging (Elasticsearch, Logstash, Kibana)
# 📈 MONITORING STACK: Metrics and alerting (Prometheus, Grafana, Alertmanager)
# 📱 NOTIFICATION:     SMS/Email gateway for alerts
# 🔍 SYSTEM METRICS:   Node Exporter for infrastructure monitoring
#
# Usage:
#   docker-compose up -d                    # Start all services
#   docker-compose up -d redis             # Start only Redis services
#   docker-compose logs -f prometheus      # View Prometheus logs
#   docker-compose down                     # Stop all services
#
# Management:
#   Use the manage-infrastructure.ps1 script for easier management
# ============================================================================

services:
  # ===========================
  # REDIS SERVICES - Caching & Session Storage
  # ===========================
  
  # Redis server for caching and session management
  redis:
    image: redis:7-alpine                     # Lightweight Redis image
    container_name: erp-redis                # Container name for easy reference
    ports:
      - "6379:6379"                          # Expose Redis port to host
    volumes:
      - redis_data:/data                     # Persist Redis data
    command: redis-server --appendonly yes --requirepass ""  # Enable persistence, no password
    restart: unless-stopped                  # Auto-restart unless manually stopped
    healthcheck:                             # Health check for monitoring
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s                          # Check every 10 seconds
      timeout: 3s                            # 3 second timeout
      retries: 3                             # Retry 3 times before marking unhealthy
    networks:
      - erp-network                          # Connect to shared network

  # Redis web UI for management and monitoring
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: erp-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379         # Connect to Redis service
    ports:
      - "8081:8081"                          # Web UI port
    depends_on:
      - redis                                # Wait for Redis to start
    networks:
      - erp-network

  # ===========================
  # ELK STACK - Centralized Logging Platform
  # ===========================
  
  # Elasticsearch: Log storage and search engine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: erp-elasticsearch
    environment:
      - node.name=elasticsearch              # Node name for cluster
      - cluster.name=erp-cluster             # Cluster name
      - discovery.type=single-node           # Single node setup (not for production clustering)
      - bootstrap.memory_lock=true           # Lock memory to prevent swapping
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"         # Java heap size (1GB min/max)
      - xpack.security.enabled=false         # Disable security for development
      - xpack.security.enrollment.enabled=false
    ulimits:                                 # Memory lock limits for performance
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - erp-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: erp-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - erp-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: erp-logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - erp-network

  # ===========================
  # MONITORING STACK (Prometheus/Grafana)
  # ===========================
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: erp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - erp-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.0
    container_name: erp-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - erp-network
    depends_on:
      - prometheus
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: erp-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - erp-network
    restart: unless-stopped

  # SMS Gateway service for sending alerts
  sms-gateway:
    build:
      context: ./monitoring/sms-gateway
      dockerfile: Dockerfile
    container_name: erp-sms-gateway
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      # SMS Configuration (replace with your actual values)
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID:-your-account-sid}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN:-your-auth-token}
      - SMS_FROM_NUMBER=${SMS_FROM_NUMBER:-+1234567890}
      - SMS_TO_NUMBERS=${SMS_TO_NUMBERS:-+1234567890}
      # Email Configuration
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-your-email@gmail.com}
      - SMTP_PASS=${SMTP_PASS:-your-app-password}
      - EMAIL_TO=${EMAIL_TO:-admin@erpprototype.com}
    networks:
      - erp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: erp-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - erp-network
    restart: unless-stopped

volumes:
  # Redis
  redis_data:
    driver: local
  
  # ELK Stack
  elasticsearch_data:
    driver: local
  
  # Monitoring
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  erp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
