global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@erpprototype.com'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'sms-alerts'
      group_wait: 10s
      repeat_interval: 10m
    - match:
        severity: warning
      receiver: 'email-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://sms-gateway:8080/webhook'
        send_resolved: true

  - name: 'sms-alerts'
    webhook_configs:
      - url: 'http://sms-gateway:8080/sms'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'admin'
            password: 'sms-secret-key'

  - name: 'email-alerts'
    webhook_configs:
      - url: 'http://sms-gateway:8080/email'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
