groups:
  - name: erp_system_alerts
    rules:
      # Service Down Alerts
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 30 seconds. Instance: {{ $labels.instance }}"

      # Health Check Failures
      - alert: HealthCheckFailed
        expr: probe_success == 0
        for: 60s
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "Health check failed for {{ $labels.job }}"
          description: "Health check for {{ $labels.job }} has been failing for more than 1 minute. Instance: {{ $labels.instance }}"

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
          service: "{{ $labels.job }}"
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 2 seconds for {{ $labels.job }}. Current value: {{ $value }}s"

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: "{{ $labels.job }}"
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for {{ $labels.job }}. Current rate: {{ $value | humanizePercentage }}"

      # Memory Usage High
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 85%. Current usage: {{ $value | humanizePercentage }}"

      # Disk Space Low
      - alert: DiskSpaceLow
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10%. Current available: {{ $value | humanizePercentage }}"

      # CPU Usage High
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80%. Current usage: {{ $value }}%"

      # Redis Connection Issues (for Identity Service)
      - alert: RedisConnectionFailed
        expr: redis_connected_clients == 0
        for: 2m
        labels:
          severity: warning
          service: "redis"
        annotations:
          summary: "Redis connection issues"
          description: "No Redis clients connected for more than 2 minutes"

      # gRPC Service Unavailable
      - alert: GrpcServiceUnavailable
        expr: grpc_server_handled_total{grpc_code!="OK"} / grpc_server_handled_total > 0.1
        for: 3m
        labels:
          severity: warning
          service: "{{ $labels.job }}"
        annotations:
          summary: "gRPC service errors"
          description: "gRPC error rate is above 10% for {{ $labels.job }}. Current rate: {{ $value | humanizePercentage }}"
